@hostname = localhost:8080
@shortcode = aaajWlId
@shortcode2 = aaa4WEWr


### Get shortUrl

POST http://{{hostname}}/shortcode HTTP/1.1
Content-Type: application/json

{ "original_url": "https://www.youtube.com", "valid_for_in_months": 1 }

### Redirect to originalUrl

GET http://{{hostname}}/{{shortcode}} HTTP/1.1



### get google

POST http://{{hostname}}/custom/shortcode HTTP/1.1
Content-Type: application/json

{
  "original_url": "https://www.google.com",
  "short_code": "aaaHu6hw",
  "valid_for_in_months": 1
}
