@hostname = localhost:8080
@shortcode = aaaCeCSK
@shortcode2 = aaa4WEWr


### Get shortUrl

POST http://{{hostname}}/v1/shortcode HTTP/1.1
Content-Type: application/json

{ "originalUrl": "https://www.youtube.com" }

### Redirect to originalUrl

GET http://{{hostname}}/v1/{{shortcode}} HTTP/1.1



### get google

GET https://www.github.com/sachin746 HTTP/1.1
